{% set name = "google-cloud-bigquery-connection" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_bigquery_connection-{{ version }}.tar.gz
  sha256: 88ce23ab6fe959d18506bfab7aca52b53059bf4ef1cff4cc93ce3a883684d2cf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - grpcio >=1.33.2,<2.0.0
    - python >={{ python_min }}
    - google-api-core >=2.11.0,<3.0.0
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    - proto-plus >=1.22.3,<2.0.0
    - protobuf >=4.25.8,<8.0.0
    - grpc-google-iam-v1 >=0.14.0,<1.0.0

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-bigquery-connection
  summary: Google Cloud Bigquery Connection API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
