{% set name = "google-cloud-bigquery-connection" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_bigquery_connection-{{ version }}.tar.gz
  sha256: fed4f41837f639525aee139f0447af7d20997bebfd78115dc8c6daec64c8002e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - grpcio >=1.59.0,<2.0.0
    - python >={{ python_min }}
    - google-api-core >=2.28.0,<3.0.0
    - google-auth >=2.14.1,<3.0.0,!=2.24.0,!=2.25.0
    - proto-plus >=1.26.1,<2.0.0
    - protobuf >=6.33.5,<8.0.0
    - grpc-google-iam-v1 >=0.14.2,<1.0.0

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-bigquery-connection
  summary: Google Cloud Bigquery Connection API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
